name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a

      - uses: actions/setup-node@main
        with:
          node-version: 22

      - name: Changed files
        id: changed
        uses: tj-actions/changed-files@v45

      - name: Build
        run: |
          echo "Build de l'application"
          node --version

      - name: Log PR title
        if: github.event_name == 'pull_request'
        run: echo "PR title"
